const axios = require('axios');

class OllamaService {
  constructor() {
    this.baseURL = process.env.OLLAMA_URL || 'http://localhost:11434';
    this.model = process.env.OLLAMA_MODEL || 'llama3.2'; // Default to llama3.2, can be changed
  }

  /**
   * Generate a response using Ollama
   * @param {string} prompt - The user's question or prompt
   * @param {object} context - Additional context data (wand_ai.json data)
   * @param {string} agentType - Type of agent (summarizer, financial-analyst, etc.)
   * @returns {Promise<string>} - Generated response
   */
  async generateResponse(prompt, context = {}, agentType = 'general') {
    try {
      // Split context into sections for faster processing
      const sections = this.splitContextIntoSections(context);
      let fullResponse = '';
      
      console.log(`Processing ${sections.length} sections for ${agentType}`);
      
      for (let i = 0; i < sections.length; i++) {
        const section = sections[i];
        const sectionPrompt = this.buildSectionPrompt(agentType, section, prompt, i, sections.length);
        
        console.log(`Processing section ${i + 1}/${sections.length}, prompt length: ${sectionPrompt.length}`);
        
        try {
          const sectionResponse = await this.generateSectionResponse(sectionPrompt);
          fullResponse += sectionResponse + ' ';
        } catch (sectionError) {
          console.warn(`Section ${i + 1} failed, using fallback:`, sectionError.message);
          fullResponse += this.getSectionFallback(agentType, section) + ' ';
        }
      }
      
      const finalResponse = fullResponse.trim() + '\n\n*This response was generated by an LLM (Ollama)*';
      console.log('Ollama streaming complete, response length:', finalResponse.length);
      return finalResponse;

      // Fallback if response format is different
      if (typeof response.data === 'string') {
        const responseText = response.data.trim();
        return `${responseText}\n\n*This response was generated by an LLM (Ollama)*`;
      }

      return 'Unable to generate response from Ollama.';
    } catch (error) {
      console.error('Ollama API Error:', error.message);
      console.error('Full error:', error);
      
      // Fallback if Ollama is not available or times out
      if (error.code === 'ECONNREFUSED' || error.code === 'ENOTFOUND' || error.code === 'ECONNABORTED') {
        console.warn('Ollama error or timeout, using fallback response');
        return this.getFallbackResponse(prompt, context, agentType);
      }
      
      // For other errors, also use fallback
      console.warn('Ollama API error, using fallback response');
      return this.getFallbackResponse(prompt, context, agentType);
    }
  }

  /**
   * Build system prompt based on agent type and context
   */
  buildSystemPrompt(agentType, context) {
    const wandAiData = context.wandAiData || {};
    const companyInfo = wandAiData.company_info || {};
    const financials = wandAiData.financials || [];
    const customerSatisfaction = wandAiData.customer_satisfaction || [];
    const salesByRegion = wandAiData.sales_by_region || [];
    const userEngagement = wandAiData.user_engagement || [];

    let systemPrompt = `You are an AI assistant helping with ${companyInfo.name || 'Wand AI'} company data analysis. `;
    
    systemPrompt += `\n\nCompany Information:\n`;
    systemPrompt += `- Company Name: ${companyInfo.name || 'Wand AI'}\n`;
    systemPrompt += `- Founded: ${companyInfo.founded || 'N/A'}\n`;
    systemPrompt += `- Mission: ${companyInfo.mission || 'N/A'}\n`;
    systemPrompt += `- Employees: ${companyInfo.employees || 'N/A'}\n`;
    systemPrompt += `- Headquarters: ${companyInfo.headquarters || 'N/A'}\n`;
    systemPrompt += `- Departments: ${(companyInfo.departments || []).join(', ')}\n`;

    if (financials.length > 0) {
      systemPrompt += `\nFinancial Data:\n`;
      financials.forEach(q => {
        systemPrompt += `- ${q.quarter}: Revenue: $${q.revenue?.toLocaleString() || 0}, Profit: $${q.profit?.toLocaleString() || 0}, Expenses: $${q.expenses?.toLocaleString() || 0}\n`;
      });
    }

    if (customerSatisfaction.length > 0) {
      systemPrompt += `\nCustomer Satisfaction Data:\n`;
      customerSatisfaction.forEach(m => {
        const rate = ((m.satisfied / m.surveyed) * 100).toFixed(1);
        systemPrompt += `- ${m.month}: ${m.surveyed} surveyed, ${m.satisfied} satisfied (${rate}%), ${m.neutral} neutral, ${m.dissatisfied} dissatisfied\n`;
      });
    }

    if (salesByRegion.length > 0) {
      systemPrompt += `\nSales by Region:\n`;
      salesByRegion.forEach(r => {
        systemPrompt += `- ${r.region}: $${r.sales?.toLocaleString() || 0}\n`;
      });
    }

    if (userEngagement.length > 0) {
      systemPrompt += `\nUser Engagement Metrics:\n`;
      userEngagement.forEach(e => {
        if (e.metric === 'feature_usage') {
          systemPrompt += `- Feature Usage: ${JSON.stringify(e.details)}\n`;
        } else {
          systemPrompt += `- ${e.metric}: ${e.last_month_average}\n`;
        }
      });
    }

    // Add agent-specific instructions
    switch (agentType) {
      case 'summarizer':
        systemPrompt += `\n\nYour role: Create concise, accurate summaries based on the provided data. Focus on key insights and main points.`;
        break;
      case 'financial-analyst':
        systemPrompt += `\n\nYour role: Analyze financial data, identify trends, calculate growth rates, and provide financial insights.`;
        break;
      case 'data-analyst':
        systemPrompt += `\n\nYour role: Perform statistical analysis, identify patterns, and provide data-driven insights.`;
        break;
      case 'chart-generator':
        systemPrompt += `\n\nYour role: Describe what charts would be useful and what insights they would show based on the data.`;
        break;
      case 'report-generator':
        systemPrompt += `\n\nYour role: Generate structured reports with sections, analysis, and recommendations.`;
        break;
      default:
        systemPrompt += `\n\nYour role: Provide comprehensive analysis and insights based on the available data.`;
    }

    systemPrompt += `\n\nAlways base your responses on the actual data provided. Be specific with numbers and percentages. If data is not available for a specific question, clearly state that.`;

    return systemPrompt;
  }

  /**
   * Fallback response when Ollama is not available
   */
  getFallbackResponse(prompt, context, agentType) {
    const wandAiData = context.wandAiData || {};
    
    // Generate dummy responses based on agent type
    switch (agentType) {
      case 'summarizer':
        return `Based on the available data for ${wandAiData.company_info?.name || 'Wand AI'}, I can see this is a growing AI company founded in 2020 with 150+ employees. The company focuses on hybrid workforce AI solutions and has shown consistent growth across multiple departments.


*This response was generated by Mock JavaScript Agent*`;
        
      case 'financial-analyst':
        const financials = wandAiData.financials || [];
        const totalRevenue = financials.reduce((sum, q) => sum + (q.revenue || 0), 0);
        const avgProfit = financials.reduce((sum, q) => sum + (q.profit || 0), 0) / (financials.length || 1);
        return `Financial Analysis: Total revenue across all quarters: $${totalRevenue.toLocaleString()}. Average quarterly profit: $${avgProfit.toLocaleString()}. The company shows steady growth with improving profit margins over time.


*This response was generated by Mock JavaScript Agent*`;
        
      case 'customer-analyst':
        const satisfaction = wandAiData.customer_satisfaction || [];
        const avgSatisfaction = satisfaction.reduce((sum, m) => sum + ((m.satisfied / m.surveyed) * 100), 0) / (satisfaction.length || 1);
        return `Customer Satisfaction Analysis: Average satisfaction rate is ${avgSatisfaction.toFixed(1)}%. Customer feedback shows positive trends with most users reporting good experiences with the AI solutions.`;
        
      case 'engagement-analyst':
        const engagement = wandAiData.user_engagement || [];
        const totalUsers = engagement.reduce((sum, e) => sum + (e.active_users || 0), 0);
        const avgSessionTime = engagement.reduce((sum, e) => sum + (e.avg_session_time || 0), 0) / (engagement.length || 1);
        return `User Engagement Analysis: Total active users: ${totalUsers.toLocaleString()}. Average session time: ${avgSessionTime.toFixed(1)} minutes. User engagement is strong with consistent daily activity patterns.`;
        
      case 'data-collector':
        return `Data Collection Complete: Successfully gathered comprehensive data from ${wandAiData.company_info?.name || 'Wand AI'} including financial records, customer satisfaction surveys, sales by region, and user engagement metrics. All data sources have been verified and structured for analysis.`;
        
      case 'data-analyst':
        return `Data Analysis Complete: Processed and analyzed all available datasets. Key findings include consistent revenue growth, high customer satisfaction rates above 85%, and strong user engagement metrics. Data patterns show positive business trends across all departments.`;
        
      case 'chart-generator':
        return `Chart Generation Complete: Created visual representations including revenue trend charts, customer satisfaction graphs, regional sales maps, and user engagement dashboards. All charts are optimized for clarity and include proper data labeling and legends.`;
        
      case 'report-generator':
        return `Report Generation Complete: Compiled comprehensive analysis report covering financial performance, customer insights, and engagement metrics. Report includes executive summary, detailed analysis, data visualizations, and strategic recommendations based on findings.`;
        
      case 'general-analyst':
        return `General Analysis Complete: Conducted thorough analysis of ${wandAiData.company_info?.name || 'Wand AI'} operations. The company demonstrates strong performance across all key metrics with consistent growth trajectory and positive market position in the AI solutions space.`;
        
      default:
        return `Analysis complete for ${wandAiData.company_info?.name || 'Wand AI'}. The company data shows positive trends across financial performance, customer satisfaction, and user engagement metrics.`;
    }
  }

  /**
   * Check if Ollama is available
   */
  async checkAvailability() {
    try {
      console.log('Testing Ollama availability at:', this.baseURL);
      const response = await axios.get(`${this.baseURL}/api/tags`, { timeout: 5000 });
      console.log('Ollama is available! Models:', response.data?.models?.map(m => m.name));
      
      // Test actual generation
      const testResponse = await axios.post(`${this.baseURL}/api/generate`, {
        model: this.model,
        prompt: 'test',
        stream: false,
        options: { num_predict: 5 }
      }, { timeout: 10000 });
      console.log('Ollama generation test successful:', testResponse.data?.response?.substring(0, 50));
      
      return { available: true, models: response.data?.models || [] };
    } catch (error) {
      console.error('Ollama availability test failed:', error.message);
      console.error('Full error:', error);
      return { available: false, error: error.message };
    }
  }

  /**
   * List available models
   */
  async listModels() {
    try {
      const response = await axios.get(`${this.baseURL}/api/tags`);
      return response.data?.models || [];
    } catch (error) {
      console.error('Error listing models:', error.message);
      return [];
    }
  }

  /**
   * Split context into smaller sections for faster processing
   */
  splitContextIntoSections(context) {
    const wandAiData = context.wandAiData || {};
    const sections = [];
    
    // Split by data type
    if (wandAiData.financials && wandAiData.financials.length > 0) {
      sections.push({ type: 'financials', data: wandAiData.financials });
    }
    
    if (wandAiData.customer_satisfaction && wandAiData.customer_satisfaction.length > 0) {
      sections.push({ type: 'customer_satisfaction', data: wandAiData.customer_satisfaction });
    }
    
    if (wandAiData.sales_by_region && wandAiData.sales_by_region.length > 0) {
      sections.push({ type: 'sales_by_region', data: wandAiData.sales_by_region });
    }
    
    if (wandAiData.user_engagement && wandAiData.user_engagement.length > 0) {
      sections.push({ type: 'user_engagement', data: wandAiData.user_engagement });
    }
    
    // Always include basic company info
    if (wandAiData.company_info) {
      sections.unshift({ type: 'company_info', data: wandAiData.company_info });
    }
    
    return sections.length > 0 ? sections : [{ type: 'basic', data: {} }];
  }
  
  /**
   * Build prompt for individual section
   */
  buildSectionPrompt(agentType, section, originalPrompt, sectionIndex, totalSections) {
    const sectionContext = this.formatSectionForPrompt(section);
    const sectionNumber = sectionIndex + 1;
    
    return `You are a ${agentType} analyzing data for Wand AI. This is section ${sectionNumber} of ${totalSections}.

${sectionContext}

User Question: ${originalPrompt}

Provide a brief analysis focusing on this section only. Keep response under 100 words.`;
  }
  
  /**
   * Format section data for prompt
   */
  formatSectionForPrompt(section) {
    switch (section.type) {
      case 'company_info':
        return `Company Info: ${JSON.stringify(section.data, null, 2)}`;
      case 'financials':
        return `Financial Data: ${JSON.stringify(section.data.slice(0, 3), null, 2)}`;
      case 'customer_satisfaction':
        return `Customer Satisfaction: ${JSON.stringify(section.data.slice(0, 2), null, 2)}`;
      case 'sales_by_region':
        return `Sales by Region: ${JSON.stringify(section.data.slice(0, 3), null, 2)}`;
      case 'user_engagement':
        return `User Engagement: ${JSON.stringify(section.data.slice(0, 2), null, 2)}`;
      default:
        return `Basic Data: ${JSON.stringify(section.data, null, 2)}`;
    }
  }
  
  /**
   * Generate response for individual section
   */
  async generateSectionResponse(prompt) {
    const response = await axios.post(`${this.baseURL}/api/generate`, {
      model: this.model,
      prompt: prompt,
      stream: false,
      options: {
        temperature: 0.1,
        top_p: 0.5,
        num_predict: 30,
        num_ctx: 256,
        repeat_penalty: 1.1,
      }
    }, {
      timeout: 10000
    });
    
    return response.data?.response?.trim() || '';
  }
  
  /**
   * Get fallback response for failed section
   */
  getSectionFallback(agentType, section) {
    return `Section analysis (${section.type}) completed using structured data.`;
  }
}

module.exports = { OllamaService };

